version: '3'
services:
  qx:
    image: itisfoundation/qooxdoo-compiler:latest
    volumes:
      - '.:/home/node/src'
    ports:
      - '8080:8080'
    working_dir: /home/node/src/${APP_DIR:-.}
    command: serve --set qx.allowUrlSettings=true
    # Open http://localhost:8080/index.html?qxenv:auth.mockBackend:true