version: '3'
services:
  qx:
    #image: itisfoundation/qooxdoo-compiler:latest
    #image: qx:master
    image: qx:${IMAGE_VERSION:-released}
    volumes:
      - '.:/home/scu/client'
    ports:
      - '${PORT:-9000}:8080'
    working_dir: /home/scu/client/${APP_DIR:-.}
    env_file:
      - secrets.env
    command: serve --set qx.allowUrlSettings=true
  #---------------------------------------------------------
  doc:
    image: http-server:latest
    volumes:
      - '.:/user/src/app'
    ports:
      - '${PORT:-9001}:8080'
    working_dir: /user/src/app/${APP_DIR:-.}
    command: api
  #---------------------------------------------------------
  test:
    image: http-server:latest
    volumes:
      - '.:/user/src/app'
    ports:
      - '${PORT:-9002}:8080'
    working_dir: /user/src/app/${APP_DIR:-.}
    command: test

    #
    # Open http://localhost:8080/index.html?qxenv:dev.enableFakeServer:true
    #